### ISSUE TITLE
Unable to run SpliceAI due to "Attribute error"

### ISSUE THREAD

**Issue by marielwiss** [Illumina/SpliceAI#106]
Hello, I am encountering an **attribute error** when attempting to run spliceai with **keras==2.9.0, tensorflow==2.9.1, h5py==3.7.0, in python 3.7.10**. In this message I have included:
  1. How I installed spliceai and tensorflow
  2. My version of listed requirements for SpliceAI to run
  3. The error message I encounter

## 1. How I installed spliceai and tensorflow
I installed spliceai and tensorflow following the README instructions:
```
mamba install -c bioconda spliceai
mamba install tensorflow
```
## 2. My version of listed requirements for SpliceAI to run
I checked that the other listed requirements were up to date as compared to the [SpliceAI/setup.py](https://github.com/Illumina/SpliceAI/blob/master/setup.py) page:

**Listed Requirements |     My Version  |                          Build |    Channel**
keras>=2.0.5  |            keras 2.9.0    |                      pypi_0  |   pypi
pyfaidx>=0.5.0   |        pyfaidx 0.7.0   |               pyh5e36f6f_1    bioconda
pysam>=0.10.0   |         pysam 0.18.0  |                       pypi_0    pypi
numpy>=1.14.0   |         numpy 1.21.1     |                    pypi_0    pypi
pandas>=0.24.2  |         pandas 1.3.1     |                    pypi_0    pypi
tensorflow>=1.2.0   |     tensorflow 2.9.1     |                pypi_0    pypi
tensorflow-gpu>=1.2.0  |  tensorflow-gpu  2.6.0  | cuda111py37h788eb59_2   |  conda-forge

## 3. Error Message
I encounter the below error message both when I do:
```
spliceai -h
spliceai -I input.vcf -O output.vcf -R genome.fa -A grch38
```

### This is the Error Message:
Traceback (most recent call last):
  File "/miniconda3/envs/gen/bin/spliceai", line 7, in <module>
    from spliceai.__main__ import main
  File "/miniconda3/envs/gen/lib/python3.7/site-packages/spliceai/__main__.py", line 5, in <module>
    from spliceai.utils import Annotator, get_delta_scores
  File "/miniconda3/envs/gen/lib/python3.7/site-packages/spliceai/utils.py", line 6, in <module>
    from keras.models import load_model
  File "/miniconda3/envs/gen/lib/python3.7/site-packages/keras/__init__.py", line 15, in <module>
    from . import layers
  File "/miniconda3/envs/gen/lib/python3.7/site-packages/keras/layers/__init__.py", line 4, in <module>
    from . import convolutional
  File "/miniconda3/envs/gen/lib/python3.7/site-packages/keras/layers/convolutional/__init__.py", line 19, in <module>
    from keras.layers.convolutional.conv1d import Conv1D
  File "/miniconda3/envs/gen/lib/python3.7/site-packages/keras/layers/convolutional/conv1d.py", line 20, in <module>
    from keras import initializers
  File "/miniconda3/envs/gen/lib/python3.7/site-packages/keras/initializers/__init__.py", line 23, in <module>
    from keras.initializers import initializers_v2
  File "/miniconda3/envs/gen/lib/python3.7/site-packages/keras/initializers/initializers_v2.py", line 20, in <module>
    from keras.dtensor import utils
  File "/miniconda3/envs/gen/lib/python3.7/site-packages/keras/dtensor/__init__.py", line 22, in <module>
    from tensorflow.compat.v2.experimental import dtensor as dtensor_api  # pylint: disable=g-import-not-at-top
  File "/miniconda3/envs/gen/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v2/experimental/dtensor/__init__.py", line 8, in <module>
    from tensorflow.dtensor.python.api import call_with_layout
  File "/miniconda3/envs/gen/lib/python3.7/site-packages/tensorflow/dtensor/python/__init__.py", line 17, in <module>
    from tensorflow.dtensor.python import gen_dtensor_ops as ops
  File "/miniconda3/envs/gen/lib/python3.7/site-packages/tensorflow/dtensor/python/gen_dtensor_ops.py", line 24, in <module>
    @_dispatch.add_fallback_dispatch_list
AttributeError: module 'tensorflow.python.util.dispatch' has no attribute 'add_fallback_dispatch_list'

### Thank you!

**Comment by sicotteh** [comment]
This is related to the issue I wrote up. SpliceAI only works with older tensorflow/keras libraries, more recent libraries have been significantly refactored and in typical python community fashion, little care was taken to maintain backward compatibility.
this is the combination I use.

tensorflow==1.15
keras==2.3.1
# I cannot remember if these next two versions are critical, but that's the ones I use.
h5py==2.10.0
numpy== 1.19

**Comment by marielwiss** [comment]
Thanks for your suggestions! I ended up getting it to work by creating a new environment and using a pip install (`pip install --user tensorflow` and `pip install --user spliceai`).
