### ISSUE TITLE
installation issue with conda

### ISSUE THREAD

**Issue by davemcg** [Illumina/SpliceAI#33]
`conda create --yes --name spliceai; conda activate spliceai; conda install --yes tensorflow=1.2-0; conda install --yes spliceai=1.2`

Running `spliceai -h` works.

But running with actual data gives this error:

```
$ spliceai -I temp/vt.VCFs.GATK__1:83083541-110778053.vcf.gz -R /data/OGVFB/resources/1000G_phase2_GRCh37/human_g1k_v37_decoy.fasta -A grch37 -O temp/spliceai.VCFs.GATK__1:83083541-110778053.vcf.gz
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data/mcgaugheyd/conda/envs/spliceai/bin/spliceai", line 12, in <module>
    sys.exit(main())
  File "/usr/local/apps/spliceai/20190507/src/spliceai/__main__.py", line 53, in main
    ann = Annotator(args.R, args.A)
  File "/usr/local/apps/spliceai/20190507/src/spliceai/utils.py", line 39, in __init__
    self.models = [load_model(resource_filename(__name__, x)) for x in paths]
  File "/usr/local/apps/spliceai/20190507/src/spliceai/utils.py", line 39, in <listcomp>
    self.models = [load_model(resource_filename(__name__, x)) for x in paths]
  File "/usr/local/apps/spliceai/20190507/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/usr/local/apps/spliceai/20190507/lib/python3.6/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/apps/spliceai/20190507/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/apps/spliceai/20190507/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/apps/spliceai/20190507/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/apps/spliceai/20190507/lib/python3.6/site-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "/usr/local/apps/spliceai/20190507/lib/python3.6/site-packages/keras/engine/network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/apps/spliceai/20190507/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/apps/spliceai/20190507/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/usr/local/apps/spliceai/20190507/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1109, in from_config
    return cls(**config)
  File "/usr/local/apps/spliceai/20190507/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/apps/spliceai/20190507/lib/python3.6/site-packages/keras/engine/input_layer.py", line 87, in __init__
    name=self.name)
  File "/usr/local/apps/spliceai/20190507/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 517, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
AttributeError: module 'tensorflow' has no attribute 'placeholder'
```

**Comment by kishorejaganathan** [comment]
When I googled your error, a lot of the links are pointing to Tensorflow 2.0. Could you open an interactive python session and just try:
`import tensorflow as tf
print(tf.__version__)`
and make sure you've installed the right version of Tensorflow (we've tested from 1.2 to 1.9)? 

Some other things you could try:
- Install tensorflow via pip
- Try python 2.7 if that's an option

**Comment by kishorejaganathan** [comment]
Could you also try installing tensorflow via
`conda install tensorflow==1.9.0`

**Comment by davemcg** [comment]
I also saw that which is why I installed tensorflow at 1.2

```
(spliceai) [mcgaugheyd@cn4177 2019_arno]$ conda list tensorflow
# packages in environment at /data/mcgaugheyd/conda/envs/spliceai:
#
# Name                    Version                   Build  Channel
tensorflow                1.2.0                    py36_0    conda-forge
```

Though when I check via python....
```
>>> import tensorflow as tf

>>> print(tf.__version__)
2.0.0
```

Uh, what happened?

**Comment by kishorejaganathan** [comment]
Yeah I figured you installed 2.0 by mistake, usually it should be == and not = for precise versions. Could you try one of:
`conda install tensorflow==1.9.0`
or 
`pip install tensorflow==1.9.0`

During the next update, I'll add a patch to make sure it works for versions 2.0 onwards as well...

**Comment by davemcg** [comment]
Installed `conda create --yes --name spliceai; conda activate spliceai; conda install --yes tensorflow==1.9-0; conda install --yes spliceai`  but now getting this error:

```
$ spliceai -h
Using TensorFlow backend.
/data/mcgaugheyd/conda/envs/spliceai/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/data/mcgaugheyd/conda/envs/spliceai/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/data/mcgaugheyd/conda/envs/spliceai/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/data/mcgaugheyd/conda/envs/spliceai/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/data/mcgaugheyd/conda/envs/spliceai/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/data/mcgaugheyd/conda/envs/spliceai/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/data/mcgaugheyd/conda/envs/spliceai/bin/spliceai", line 8, in <module>
    from spliceai.__main__ import main
  File "/data/mcgaugheyd/conda/envs/spliceai/lib/python3.6/site-packages/spliceai/__main__.py", line 4, in <module>
    from spliceai.utils import Annotator, get_delta_scores
  File "/data/mcgaugheyd/conda/envs/spliceai/lib/python3.6/site-packages/spliceai/utils.py", line 5, in <module>
    from keras.models import load_model
  File "/data/mcgaugheyd/conda/envs/spliceai/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/data/mcgaugheyd/conda/envs/spliceai/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/data/mcgaugheyd/conda/envs/spliceai/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/data/mcgaugheyd/conda/envs/spliceai/lib/python3.6/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/data/mcgaugheyd/conda/envs/spliceai/lib/python3.6/site-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/data/mcgaugheyd/conda/envs/spliceai/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 54, in <module>
    get_graph = tf_keras_backend.get_graph
AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'get_graph'
```

**Comment by kishorejaganathan** [comment]
Also seems like a 2.0 issue. Could you try installing tensorflow with pip?

**Comment by kishorejaganathan** [comment]
Is this still an issue? I'm reading that it is important to use certain versions of Keras with certain versions of Tensorflow. Could you try Keras==2.2.4 with Tensorflow 1.9 if you still couldn't get this to work?

**Comment by mcortes-lopez** [comment]
I had a similar issue and I tried the installation with Keras 2.24 and Tensorflow 1.9 but the error that i currently have is: 


Traceback (most recent call last):
  File "/home/mcortesl/.conda/envs/spliceai/bin/spliceai", line 12, in <module>
    sys.exit(main())
  File "/home/mcortesl/.conda/envs/spliceai/lib/python3.6/site-packages/spliceai/__main__.py", line 53, in main
    ann = Annotator(args.R, args.A)
  File "/home/mcortesl/.conda/envs/spliceai/lib/python3.6/site-packages/spliceai/utils.py", line 20, in __init__
    self.genes = df['#NAME'].get_values()
  File "/home/mcortesl/.conda/envs/spliceai/lib/python3.6/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'get_values'

**Comment by JakeHagen** [comment]
@mcortes-lopez I think that is a pandas 1.0 issue. Try pandas 0.25.3

**Comment by kishorejaganathan** [comment]
@mcortes-lopez: As pointed out by @JakeHagen, this is a pandas 1.0 issue. We have resolved this in the latest update to the git repo, so you should not have this issue if you clone it now. Alternately, you can also try downgrading pandas version to something like 0.24.2 and that should work as well...

**Comment by bw2** [comment]
Looks like tensorflow v1.9.0 is no longer available on PyPI
This works instead:
```
python3 -m pip install tensorflow==1.15.3
```
