### ISSUE TITLE
Impossible output shape error

### ISSUE THREAD

**Issue by AldoCP** [Illumina/SpliceAI#4]
I ran the following command: 

`spliceai -I inputfile.vcf -O runaiM.vcf -R ucsc.hg19.fasta -A GENCODE.V29LIFT37.BASIC.TXT`

and got the output below. As reference, the input file includes 522 variants, and I get an output vcf file with 58 variants (and then spliceai crashes). 11 of those 58 variants are fully annotated, and the rest have mostly "SpliceAI=C|.|.|.|.|.|.|.|.|.". Any clues on how to fix it? Thanks! 

```
/home/users/aldocp/.local/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In fut
ure, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using Theano backend.
/home/users/aldocp/.local/lib/python2.7/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manuall
y.
  warnings.warn('No training configuration found in save file: '
Traceback (most recent call last):
  File "/home/users/aldocp/.local/bin/spliceai", line 11, in <module>
    sys.exit(main())
  File "/home/users/aldocp/.local/lib/python2.7/site-packages/spliceai/__main__.py", line 53, in main
    scores = get_delta_scores(record, ann)
  File "/home/users/aldocp/.local/lib/python2.7/site-packages/spliceai/utils.py", line 109, in get_delta_scores
    Y0 = np.asarray(ann.models[0].predict(X_ref))
  File "/home/users/aldocp/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1169, in predict
    steps=steps)
  File "/home/users/aldocp/.local/lib/python2.7/site-packages/keras/engine/training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "/home/users/aldocp/.local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 1388, in __call__
    return self.function(*inputs)
  File "/share/software/user/open/py-theano/1.0.1_py27/lib/python2.7/site-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/share/software/user/open/py-theano/1.0.1_py27/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/share/software/user/open/py-theano/1.0.1_py27/lib/python2.7/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
ValueError: CorrMM: impossible output shape
  bottom shape: 1 x 32 x 0 x 1
  weights shape: 3 x 32 x 1 x 1
  top shape: 1 x 3 x 0 x 1

Apply node that caused the error: CorrMM{valid, (1, 1), (1, 1), 1 False}(Elemwise{Add}[(0, 0)].0, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 1286
Inputs types: [TensorType(float32, (False, False, False, True)), TensorType(float32, (False, False, False, True))]
Inputs shapes: [(1, 32, 0, 1), (3, 32, 1, 1)]
Inputs strides: [(1208704, 37772, 4, 4), (4, 12, -4, -4)]
Inputs values: [array([], shape=(1, 32, 0, 1), dtype=float32), 'not shown']
Outputs clients: [[InplaceDimShuffle{0,2,3,1}(CorrMM{valid, (1, 1), (1, 1), 1 False}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/home/users/aldocp/.local/lib/python2.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/users/aldocp/.local/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/users/aldocp/.local/lib/python2.7/site-packages/keras/engine/network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "/home/users/aldocp/.local/lib/python2.7/site-packages/keras/engine/network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/home/users/aldocp/.local/lib/python2.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/users/aldocp/.local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 163, in call
    dilation_rate=self.dilation_rate[0])
  File "/home/users/aldocp/.local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 2096, in conv1d
    data_format=data_format, dilation_rate=dilation_rate)
  File "/home/users/aldocp/.local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 2134, in conv2d
    filter_dilation=dilation_rate)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

```

**Comment by kishorejaganathan** [comment]
The models were trained with Tensorflow as the backend, so the software should be used with Tensorflow as the backend and not Theano. Once you make the switch, try using the examples/input.vcf file as input and see if you can produce the examples/output.vcf file. Additionally, you can also run 

`python setup.py test`

and make sure all tests pass.

**Comment by AldoCP** [comment]
That's correct, thanks for the feedback -- It's worth noting that I had the issue on a computer that had both Theano and Tensorflow installed: both pip and github installers picked Theano as default. Weird, pip did not give any warning. Github install gave errors only when doing `python setup.py test`, but not during the initial setup. 

Afterward, I tried on another environment and pip chose Tensorflow. Then it worked.

**Comment by kishorejaganathan** [comment]
Glad to hear that the issue is resolved. This link https://keras.io/backend/ has information on setting the backend when multiple options are available.
