### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by Echopei** [Illumina/SpliceAI#46]
Using TensorFlow backend.

2020-05-21 02:23:54.313276: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-05-21 02:23:54.313341: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-05-21 02:23:54.313397: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (3016ca31e4f9): /proc/driver/nvidia/version does not exist
2020-05-21 02:23:54.313774: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-21 02:23:54.330051: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2000140000 Hz
2020-05-21 02:23:54.337342: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x61a52a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-21 02:23:54.337397: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
/usr/local/lib/python3.6/site-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
[W::vcf_parse] INFO 'callstatus' is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'AF' is not defined in the header, assuming Type=String
[E::vcf_format] Invalid BCF, the INFO index is too large
Traceback (most recent call last):
  File "/usr/local/bin/spliceai", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/spliceai/__main__.py", line 75, in main
    output.write(record)
  File "pysam/libcbcf.pyx", line 4400, in pysam.libcbcf.VariantFile.write
  File "pysam/libcbcf.pyx", line 4437, in pysam.libcbcf.VariantFile.write
OSError: [Errno 22] b'Invalid argument'

**Comment by kishorejaganathan** [comment]
There are a couple of issues with your setup:
- Tensorflow: This error occurs usually when there is a version mismatch. Could you open an interactive python session and just try "import tensorflow"? Most likely, you will receive the same error messages. What version of python and tensorflow are you using? And are you using tensorflow-gpu? If yes, which version of CUDA are you using? This error goes away once you use the right version of tensorflow-gpu and CUDA.
- The VCF errors are due to the fact that the header information is insufficient. Please take a look at the examples/input.vcf file in the git repository. You can copy paste the header if you're using GRCh37/hg19, otherwise use the file as template to create a new header. Could you try using that file as input and see if you can reproduce examples/output.vcf?

**Comment by Echopei** [comment]
1. "import tensorflow" cannot receive same error messages. I am not using tensorflow-gpu.
python version Python 3.6.8
tensorflow             2.2.0      
tensorflow-estimator   2.2.0 
2. vcf errors is solved

**Comment by kishorejaganathan** [comment]
The formatting requirements come from pysam, which we use to parse the VCFs. If you are indeed able to reproduce the output.vcf file, then you can ignore all the warnings - you are all set.

**Comment by Echopei** [comment]
> The formatting requirements come from pysam, which we use to parse the VCFs. If you are indeed able to reproduce the output.vcf file, then you can ignore all the warnings - you are all set.

OK, I will ignore this
 E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
