### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by Swanthana-bioinfo** [Illumina/SpliceAI#49]
Hello, 
I am trying to run spliceai on singulairty interactive mode, below is the attribute error i see. I have python3.6 installed.

spliceai -I /home/input.vcf.gz -O /home/output.vcf -R /home/ucsc.fa -A grch38 
Using TensorFlow backend.
2020-06-12 10:42:28.533297: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-06-12 10:42:28.535179: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Traceback (most recent call last):
  File "/usr/local/bin/spliceai", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/spliceai/__main__.py", line 69, in main
    ann = Annotator(args.R, args.A)
  File "/usr/local/lib/python3.6/dist-packages/spliceai/utils.py", line 21, in __init__
    self.genes = df['#NAME'].get_values()
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'get_values'

**Comment by kishorejaganathan** [comment]
I believe you're using an older version of SpliceAI, please use the latest one (where get_values has been replaced with to_numpy).

**Comment by Swanthana-bioinfo** [comment]
Thanks for the quick reply, i have updated it to newer version. But it worked for few minutes and crashed, here is the log file i have
Last login: Fri Jun 12 16:19:24 on ttys000
swan@SOMGENFVFC80T5L414 ~ % longleaf
|----------------------------------------------------------------------|
|     The University of North Carolina at Chapel Hill                  |
|     ***********************************************                  |
|     Unauthorized access to this system is prohibited.                |
|                                                                      |
| This is a University system intended for University purposes         |
| only. The University reserves the right to monitor the use of        |
| this system as required to ensure its stability, availability,       |
| and security.                                                        |
|                                                                      |
| Please report any problems to "help@unc.edu", or 962-HELP,           |
| or go to https://its.unc.edu/research-computing/contact-us-directly/ |
| to submit a help request.                                            |
|----------------------------------------------------------------------|

Password: 
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
Warning: Your password will expire in 240 days on Wed Feb 10 15:15:00 2021
Last login: Fri Jun 12 14:40:55 2020 from client-172-17-19-112.vpn.unc.edu
-------------------------------------------------
                 Welcome to
                  longleaf-login2.its.unc.edu
-------------------------------------------------
FQDN: longleaf-login2.its.unc.edu
OS: RedHat 7 x86_64
IP:  team0.2253: 172.26.113.2,  lo: 127.0.0.1,  team0:  em4:  em1:  em3:  em2:  team0.334: 152.2.94.12, 
KERNEL: 3.10.0-1062.el7.x86_64
IS VIRTUAL: physical

Processor: 24 x Intel(R) Xeon(R) CPU E5-2643 v3 @ 3.40GHz
Memory: 257565

Salt Version: 2019.2.0

Web Portal for Longleaf now available: https://ondemand.rc.unc.edu

Restoring modules to user's default, for system: "longleaf"
[swan@longleaf-login2 ~]$ 
[swan@longleaf-login2 ~]$ 
[swan@longleaf-login2 ~]$ 
[swan@longleaf-login2 ~]$ sjobs
JOBID     PARTITION  ST  TIME        TIME_LIMITNODES  NODELIST(REASON)  CPUS  NAME
61471433  volta-gpu  R   2-19:58:52  4-00:00:001      g0306             1     gridss
[swan@longleaf-login2 ~]$ 
[swan@longleaf-login2 ~]$ 
[swan@longleaf-login2 ~]$ 
[swan@longleaf-login2 ~]$ cd Gridss/
[swan@longleaf-login2 Gridss]$ ls
60707-F.BHLM7KDMXX_L001_GTAGAGGA-TATCCTCT+BHLM7KDMXX_L002_GTAGAGGA-TATCCTCT.bam.gridss.working
gridss.full.20200611_091330.g0312.279243.log
gridss.full.20200612_123914.g0306.260926.log
gridss_latest.sif
gridss.timing.20200611_091330.g0312.279243.log
gridss.timing.20200612_123914.g0306.260926.log
run_batch.slurm
run_gridss.sh
run-gridss-swan.err
run-gridss-swan.log
[swan@longleaf-login2 Gridss]$ less run-gridss-swan.err
[swan@longleaf-login2 Gridss]$ ls -lah
total 669M
drwxr-xr-x  3 swan users 4.0K Jun 12 12:39 .
drwx------ 40 swan users 8.0K Jun 12 16:53 ..
drwxrwxrwx  2 swan users  40K Jun 12 12:40 60707-F.BHLM7KDMXX_L001_GTAGAGGA-TATCCTCT+BHLM7KDMXX_L002_GTAGAGGA-TATCCTCT.bam.gridss.working
-rw-r--r--  1 swan users 132K Jun 11 20:26 gridss.full.20200611_091330.g0312.279243.log
-rw-r--r--  1 swan users  13K Jun 12 12:41 gridss.full.20200612_123914.g0306.260926.log
-rwxr-xr-x  1 swan users 666M Jun  8 14:21 gridss_latest.sif
-rw-r--r--  1 swan users 9.4K Jun 11 20:26 gridss.timing.20200611_091330.g0312.279243.log
-rw-r--r--  1 swan users 4.2K Jun 12 12:41 gridss.timing.20200612_123914.g0306.260926.log
-rw-r--r--  1 swan users 1002 Jun 12 08:35 run_batch.slurm
-rw-r--r--  1 swan users 4.0K Jun 11 09:08 .run_batch.slurm.swp
-rw-r--r--  1 swan users  981 Jun 10 09:02 run_gridss.sh
-rw-r--r--  1 swan users  12K Jun  8 15:56 .run_gridss.sh.swp
-rw-r--r--  1 swan users 2.8K Jun 12 12:39 run-gridss-swan.err
-rw-r--r--  1 swan users    0 Jun 12 12:39 run-gridss-swan.log
[swan@longleaf-login2 Gridss]$ rm .run_gridss.sh.swp
[swan@longleaf-login2 Gridss]$ rm .run_batch.slurm.swp
[swan@longleaf-login2 Gridss]$ ls -lah
total 669M
drwxr-xr-x  3 swan users 4.0K Jun 15 08:39 .
drwx------ 40 swan users 8.0K Jun 12 16:53 ..
drwxrwxrwx  2 swan users  40K Jun 12 12:40 60707-F.BHLM7KDMXX_L001_GTAGAGGA-TATCCTCT+BHLM7KDMXX_L002_GTAGAGGA-TATCCTCT.bam.gridss.working
-rw-r--r--  1 swan users 132K Jun 11 20:26 gridss.full.20200611_091330.g0312.279243.log
-rw-r--r--  1 swan users  13K Jun 12 12:41 gridss.full.20200612_123914.g0306.260926.log
-rwxr-xr-x  1 swan users 666M Jun  8 14:21 gridss_latest.sif
-rw-r--r--  1 swan users 9.4K Jun 11 20:26 gridss.timing.20200611_091330.g0312.279243.log
-rw-r--r--  1 swan users 4.2K Jun 12 12:41 gridss.timing.20200612_123914.g0306.260926.log
-rw-r--r--  1 swan users 1002 Jun 12 08:35 run_batch.slurm
-rw-r--r--  1 swan users  981 Jun 10 09:02 run_gridss.sh
-rw-r--r--  1 swan users 2.8K Jun 12 12:39 run-gridss-swan.err
-rw-r--r--  1 swan users    0 Jun 12 12:39 run-gridss-swan.log
[swan@longleaf-login2 Gridss]$ ls -lah 
total 669M
drwxr-xr-x  3 swan users 4.0K Jun 15 08:39 .
drwx------ 40 swan users 8.0K Jun 12 16:53 ..
drwxrwxrwx  2 swan users  40K Jun 12 12:40 60707-F.BHLM7KDMXX_L001_GTAGAGGA-TATCCTCT+BHLM7KDMXX_L002_GTAGAGGA-TATCCTCT.bam.gridss.working
-rw-r--r--  1 swan users 132K Jun 11 20:26 gridss.full.20200611_091330.g0312.279243.log
-rw-r--r--  1 swan users  13K Jun 12 12:41 gridss.full.20200612_123914.g0306.260926.log
-rwxr-xr-x  1 swan users 666M Jun  8 14:21 gridss_latest.sif
-rw-r--r--  1 swan users 9.4K Jun 11 20:26 gridss.timing.20200611_091330.g0312.279243.log
-rw-r--r--  1 swan users 4.2K Jun 12 12:41 gridss.timing.20200612_123914.g0306.260926.log
-rw-r--r--  1 swan users 1002 Jun 12 08:35 run_batch.slurm
-rw-r--r--  1 swan users  981 Jun 10 09:02 run_gridss.sh
-rw-r--r--  1 swan users 2.8K Jun 12 12:39 run-gridss-swan.err
-rw-r--r--  1 swan users    0 Jun 12 12:39 run-gridss-swan.log
[swan@longleaf-login2 Gridss]$ sjobs
JOBID     PARTITION  ST  TIME        TIME_LIMITNODES  NODELIST(REASON)  CPUS  NAME
61471433  volta-gpu  R   2-20:00:34  4-00:00:001      g0306             1     gridss
[swan@longleaf-login2 Gridss]$ cd ~
[swan@longleaf-login2 ~]$ ls /nas/longleaf/apps/spliceai/
1.3  1.3.1
[swan@longleaf-login2 ~]$ ls /nas/longleaf/apps/spliceai/1.3.1
examples  simg
[swan@longleaf-login2 ~]$ ls /nas/longleaf/apps/spliceai/1.3.1/examples/
run_batch.slurm  run_interactive.slurm
[swan@longleaf-login2 ~]$ ls /nas/longleaf/apps/spliceai/1.3.1/simg/
build.image  inspect.image  shell.image  Singularity  spliceai-1.3.1-py3-cuda10.1-ubuntu18.04.simg
[swan@longleaf-login2 ~]$ cd /proj/berglab/users/swan/
[swan@longleaf-login2 swan]$ ls
NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.annotated.indel.vcf
NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.annotated.snv.vcf
NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.indel.vcf
NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.need.annotations.vcf.gz
NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.need.annotations.vcf.gz.csi
NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.not.annotated.snv.vcf.gz
NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.not.annotated.snv.vcf.gz.csi
NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC-spliceai-run.vcf
NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.snv.bcf
NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.snv.vcf
run_bcftools.sh
[swan@longleaf-login2 swan]$ cd ~
[swan@longleaf-login2 ~]$ cd SpliceAI/
[swan@longleaf-login2 SpliceAI]$ ls
COPYRIGHT  examples  LICENSE  NOTICE  README.md  setup.py  spliceai  swan_testing  tests
[swan@longleaf-login2 SpliceAI]$ cd swan_testing/
[swan@longleaf-login2 swan_testing]$ LS
-bash: LS: command not found
[swan@longleaf-login2 swan_testing]$ ls
run-61472323.log  run_batch.slurm  run_spliceai_interactive.sh
[swan@longleaf-login2 swan_testing]$ vi run_batch.slurm 
[swan@longleaf-login2 swan_testing]$ 
[swan@longleaf-login2 swan_testing]$ 
[swan@longleaf-login2 swan_testing]$ 
[swan@longleaf-login2 swan_testing]$ less run-61472323.log 
[swan@longleaf-login2 swan_testing]$ ls ../
COPYRIGHT  examples  LICENSE  NOTICE  README.md  setup.py  spliceai  swan_testing  tests
[swan@longleaf-login2 swan_testing]$ ls ../spliceai/annotations/
grch37.txt  grch38.txt
[swan@longleaf-login2 swan_testing]$ cd ../swan_testing/
[swan@longleaf-login2 swan_testing]$ vi run_batch.slurm 
[swan@longleaf-login2 swan_testing]$ less ../spliceai/annotations/grch38.txt 
[swan@longleaf-login2 swan_testing]$ la
-bash: la: command not found
[swan@longleaf-login2 swan_testing]$ ls
run-61472323.log  run_batch.slurm  run_spliceai_interactive.sh
[swan@longleaf-login2 swan_testing]$ rm run-61472323.log 
[swan@longleaf-login2 swan_testing]$ 
[swan@longleaf-login2 swan_testing]$ 
[swan@longleaf-login2 swan_testing]$ sbatch run_batch.slurm 
Submitted batch job 61855607
[swan@longleaf-login2 swan_testing]$ 
[swan@longleaf-login2 swan_testing]$ 
[swan@longleaf-login2 swan_testing]$ sjobs
JOBID     PARTITION  ST  TIME        TIME_LIMITNODES  NODELIST(REASON)  CPUS  NAME
61471433  volta-gpu  R   2-20:07:51  4-00:00:001      g0306             1     gridss
61855607  volta-gpu  R   0:04        12:00:001        g0307             1     spliceai
[swan@longleaf-login2 swan_testing]$ 
[swan@longleaf-login2 swan_testing]$ 
[swan@longleaf-login2 swan_testing]$ ls
run-61855607.log  run_batch.slurm  run_spliceai_interactive.sh
[swan@longleaf-login2 swan_testing]$ less run-61855607.log 
[swan@longleaf-login2 swan_testing]$ sjobs
JOBID     PARTITION  ST  TIME        TIME_LIMITNODES  NODELIST(REASON)  CPUS  NAME
61471433  volta-gpu  R   2-20:08:19  4-00:00:001      g0306             1     gridss
[swan@longleaf-login2 swan_testing]$ vi run_batch.slurm 
[swan@longleaf-login2 swan_testing]$ 
[swan@longleaf-login2 swan_testing]$ 
[swan@longleaf-login2 swan_testing]$ ls
run-61855607.log  run_batch.slurm  run_spliceai_interactive.sh
[swan@longleaf-login2 swan_testing]$ rm run-61855607.log 
[swan@longleaf-login2 swan_testing]$ sbatch run_batch.slurm 
Submitted batch job 61855628
[swan@longleaf-login2 swan_testing]$ 
[swan@longleaf-login2 swan_testing]$ sjobs
JOBID     PARTITION  ST  TIME        TIME_LIMITNODES  NODELIST(REASON)  CPUS  NAME
61855628  volta-gpu  PD  0:00        12:00:001        (None)            1     spliceai
61471433  volta-gpu  R   2-20:11:43  4-00:00:001      g0306             1     gridss
[swan@longleaf-login2 swan_testing]$ sjobs
JOBID     PARTITION  ST  TIME        TIME_LIMITNODES  NODELIST(REASON)  CPUS  NAME
61471433  volta-gpu  R   2-20:11:48  4-00:00:001      g0306             1     gridss
61855628  volta-gpu  R   0:01        12:00:001        g0307             1     spliceai
[swan@longleaf-login2 swan_testing]$ ls
run-61855628.log  run_batch.slurm  run_spliceai_interactive.sh
[swan@longleaf-login2 swan_testing]$ less run-61855628.log 
[swan@longleaf-login2 swan_testing]$ less run-61855628.log 
[swan@longleaf-login2 swan_testing]$ less run-61855628.log 
[swan@longleaf-login2 swan_testing]$ sjobs
JOBID     PARTITION  ST  TIME        TIME_LIMITNODES  NODELIST(REASON)  CPUS  NAME
61471433  volta-gpu  R   2-20:12:32  4-00:00:001      g0306             1     gridss
61855628  volta-gpu  R   0:45        12:00:001        g0307             1     spliceai
[swan@longleaf-login2 swan_testing]$ less run-61855628.log 
[swan@longleaf-login2 swan_testing]$ sjobs
JOBID     PARTITION  ST  TIME        TIME_LIMITNODES  NODELIST(REASON)  CPUS  NAME
61471433  volta-gpu  R   2-20:14:50  4-00:00:001      g0306             1     gridss
61855628  volta-gpu  R   3:03        12:00:001        g0307             1     spliceai
[swan@longleaf-login2 swan_testing]$ less run-61855628.log 
[swan@longleaf-login2 swan_testing]$ sjobs
JOBID     PARTITION  ST  TIME        TIME_LIMITNODES  NODELIST(REASON)  CPUS  NAME
61471433  volta-gpu  R   2-20:16:21  4-00:00:001      g0306             1     gridss
61855628  volta-gpu  R   4:34        12:00:001        g0307             1     spliceai
[swan@longleaf-login2 swan_testing]$ less run-61855628.log 
[swan@longleaf-login2 swan_testing]$ ls -lah /proj/berglab/users/swan/
total 318M
drwxr-sr-x 2 swan rc_berglab_psx  851 Jun 12 09:01 .
drwxrws--T 5 root rc_berglab_psx   73 Jun  9 14:19 ..
-rw-r--r-- 1 swan rc_berglab_psx 7.9M Jun 11 16:31 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.annotated.indel.vcf
-rw-r--r-- 1 swan rc_berglab_psx 100M Jun 11 11:47 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.annotated.snv.vcf
-rw-r--r-- 1 swan rc_berglab_psx  22M Jun 11 16:11 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.indel.vcf
-rw-r--r-- 1 swan rc_berglab_psx 2.6M Jun 11 16:35 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.need.annotations.vcf.gz
-rw-r--r-- 1 swan rc_berglab_psx  63K Jun 11 16:36 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.need.annotations.vcf.gz.csi
-rw-r--r-- 1 swan rc_berglab_psx 3.8M Jun 11 13:06 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.not.annotated.snv.vcf.gz
-rw-r--r-- 1 swan rc_berglab_psx  98K Jun 11 13:11 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.not.annotated.snv.vcf.gz.csi
-rw-r--r-- 1 swan rc_berglab_psx 2.5M Jun 15 08:55 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC-spliceai-run.vcf
-rw-r--r-- 1 swan rc_berglab_psx  22M Jun  9 16:27 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.snv.bcf
-rw-r--r-- 1 swan rc_berglab_psx 122M Jun 10 10:10 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.snv.vcf
-rw-r--r-- 1 swan rc_berglab_psx  730 Jun 11 14:02 run_bcftools.sh
[swan@longleaf-login2 swan_testing]$ sjobs
JOBID     PARTITION  ST  TIME        TIME_LIMITNODES  NODELIST(REASON)  CPUS  NAME
61471433  volta-gpu  R   2-20:22:17  4-00:00:001      g0306             1     gridss
61855628  volta-gpu  R   10:30       12:00:001        g0307             1     spliceai
[swan@longleaf-login2 swan_testing]$ ls -lah /proj/berglab/users/swan/
total 326M
drwxr-sr-x 2 swan rc_berglab_psx  851 Jun 12 09:01 .
drwxrws--T 5 root rc_berglab_psx   73 Jun  9 14:19 ..
-rw-r--r-- 1 swan rc_berglab_psx 7.9M Jun 11 16:31 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.annotated.indel.vcf
-rw-r--r-- 1 swan rc_berglab_psx 100M Jun 11 11:47 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.annotated.snv.vcf
-rw-r--r-- 1 swan rc_berglab_psx  22M Jun 11 16:11 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.indel.vcf
-rw-r--r-- 1 swan rc_berglab_psx 2.6M Jun 11 16:35 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.need.annotations.vcf.gz
-rw-r--r-- 1 swan rc_berglab_psx  63K Jun 11 16:36 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.need.annotations.vcf.gz.csi
-rw-r--r-- 1 swan rc_berglab_psx 3.8M Jun 11 13:06 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.not.annotated.snv.vcf.gz
-rw-r--r-- 1 swan rc_berglab_psx  98K Jun 11 13:11 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.not.annotated.snv.vcf.gz.csi
-rw-r--r-- 1 swan rc_berglab_psx 9.5M Jun 15 09:01 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC-spliceai-run.vcf
-rw-r--r-- 1 swan rc_berglab_psx  22M Jun  9 16:27 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.snv.bcf
-rw-r--r-- 1 swan rc_berglab_psx 122M Jun 10 10:10 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.snv.vcf
-rw-r--r-- 1 swan rc_berglab_psx  730 Jun 11 14:02 run_bcftools.sh
[swan@longleaf-login2 swan_testing]$ ls -lah /proj/berglab/users/swan/
total 331M
drwxr-sr-x 2 swan rc_berglab_psx  851 Jun 12 09:01 .
drwxrws--T 5 root rc_berglab_psx   73 Jun  9 14:19 ..
-rw-r--r-- 1 swan rc_berglab_psx 7.9M Jun 11 16:31 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.annotated.indel.vcf
-rw-r--r-- 1 swan rc_berglab_psx 100M Jun 11 11:47 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.annotated.snv.vcf
-rw-r--r-- 1 swan rc_berglab_psx  22M Jun 11 16:11 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.indel.vcf
-rw-r--r-- 1 swan rc_berglab_psx 2.6M Jun 11 16:35 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.need.annotations.vcf.gz
-rw-r--r-- 1 swan rc_berglab_psx  63K Jun 11 16:36 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.need.annotations.vcf.gz.csi
-rw-r--r-- 1 swan rc_berglab_psx 3.8M Jun 11 13:06 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.not.annotated.snv.vcf.gz
-rw-r--r-- 1 swan rc_berglab_psx  98K Jun 11 13:11 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.not.annotated.snv.vcf.gz.csi
-rw-r--r-- 1 swan rc_berglab_psx  15M Jun 15 09:04 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC-spliceai-run.vcf
-rw-r--r-- 1 swan rc_berglab_psx  22M Jun  9 16:27 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.snv.bcf
-rw-r--r-- 1 swan rc_berglab_psx 122M Jun 10 10:10 NCG-20003-00.BH7F7YBBXY_L004_CCTAATCC.spliceai.snv.vcf
-rw-r--r-- 1 swan rc_berglab_psx  730 Jun 11 14:02 run_bcftools.sh
[swan@longleaf-login2 swan_testing]$ less run-61855628.log 
[swan@longleaf-login2 swan_testing]$ sjobs
JOBID     PARTITION  ST  TIME        TIME_LIMITNODES  NODELIST(REASON)  CPUS  NAME
61471433  volta-gpu  R   2-20:43:04  4-00:00:001      g0306             1     gridss
[swan@longleaf-login2 swan_testing]$ less run-61855628.log 
[swan@longleaf-login2 swan_testing]$ less run-61855628.log 

2020-06-15 08:51:12.953875: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-15 08:51:13.050069: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-06-15 08:51:13.192566: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-06-15 08:51:13.334814: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-06-15 08:51:13.412529: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-06-15 08:51:13.413095: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-15 08:51:13.417279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-06-15 08:51:13.418690: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-06-15 08:51:13.436570: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400000000 Hz
2020-06-15 08:51:13.437177: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x654c460 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-15 08:51:13.437229: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-15 08:51:13.813090: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x65ba360 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-06-15 08:51:13.813245: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-SXM2-16GB, Compute Capability 7.0
2020-06-15 08:51:13.815621: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:1a:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.75GiB deviceMemoryBandwidth: 836.37GiB/s
2020-06-15 08:51:13.815900: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-15 08:51:13.815925: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-15 08:51:13.815976: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-06-15 08:51:13.815997: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-06-15 08:51:13.816018: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-06-15 08:51:13.816039: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-06-15 08:51:13.816055: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-15 08:51:13.819456: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-06-15 08:51:13.819709: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-15 08:51:16.846547: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-15 08:51:16.847259: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-06-15 08:51:16.847300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-06-15 08:51:16.852007: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14949 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:1a:00.0, compute capability: 7.0)
2020-06-15 08:52:11.982675: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-15 08:52:21.681460: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
(END)

Let me know what else I can do for it to work. Thank you.

**Comment by kishorejaganathan** [comment]
There's nothing in the logs suggesting a crash. Could you look at the output and let me know which variant caused this issue? Also, could you try using the examples/input.vcf file as input and see if you can reproduce the examples/output.vcf file as the output?

**Comment by kishorejaganathan** [comment]
Closing due to inactivity, please feel free to reopen if the issue is still valid.
