### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by greekkey** [Illumina/SpliceAI#50]
Hello! I am trying to use SpliceAI 1.3.1 on Ubuntu 14.04 operating system. When I was running the sample input file, I got an ImportError (vide infra). 
Thank you in advance!
----------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ngs/program/anaconda3/bin/spliceai", line 7, in <module>
    from spliceai.__main__ import main
  File "/home/ngs/program/anaconda3/lib/python3.6/site-packages/spliceai/__main__.py", line 5, in <module>
    from spliceai.utils import Annotator, get_delta_scores
  File "/home/ngs/program/anaconda3/lib/python3.6/site-packages/spliceai/utils.py", line 2, in <module>
    import pandas as pd
  File "/home/ngs/program/anaconda3/lib/python3.6/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/home/ngs/program/anaconda3/lib/python3.6/site-packages/pandas/core/api.py", line 5, in <module>
    from pandas.core.arrays.integer import (
  File "/home/ngs/program/anaconda3/lib/python3.6/site-packages/pandas/core/arrays/__init__.py", line 13, in <module>
    from .sparse import SparseArray  # noqa: F401
  File "/home/ngs/program/anaconda3/lib/python3.6/site-packages/pandas/core/arrays/sparse/__init__.py", line 3, in <module>
    from pandas.core.arrays.sparse.accessor import SparseAccessor, SparseFrameAccessor
  File "/home/ngs/program/anaconda3/lib/python3.6/site-packages/pandas/core/arrays/sparse/accessor.py", line 10, in <module>
    from pandas.core.arrays.sparse.array import SparseArray
  File "/home/ngs/program/anaconda3/lib/python3.6/site-packages/pandas/core/arrays/sparse/array.py", line 46, in <module>
    from pandas.core.indexers import check_array_indexer
ImportError: cannot import name 'check_array_indexer'

**Comment by kishorejaganathan** [comment]
Seems similar to https://github.com/deezer/spleeter/issues/279 Could you try installing pandas first with <pip install pandas==1.0.1> and then installing SpliceAI?

**Comment by greekkey** [comment]
@kishorejaganathan I re-installed pandas as you suggested and solved the problem. Thank you very much!
