### ISSUE TITLE
ImportError libcrypto.so.1.0.0 (via conda)

### ISSUE THREAD

**Issue by Jjuj66** [Illumina/SpliceAI#68]
Hi,
Got this error while trying to run spliceAI.
I installed it via conda.

```
Traceback (most recent call last):
  File "/shared/home/adonkpegan/.conda/envs/python3/bin/spliceai", line 7, in <module>
    from spliceai.__main__ import main
  File "/shared/home/adonkpegan/.conda/envs/python3/lib/python3.6/site-packages/spliceai/__main__.py", line 4, in <module>
    import pysam
  File "/shared/home/adonkpegan/.conda/envs/python3/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```
What can i do ?
Thanks

**Comment by kishorejaganathan** [comment]
Could you try installing pysam separately first, and then install SpliceAI? If that doesn't work, could you try the installations via pip?

**Comment by Jjuj66** [comment]
Tried to install pysam first, didn't work, had the same error. Installed it via pip, and it's working :)
