### ISSUE TITLE
TypeError: Parameter to MergeFrom() must be instance of same class

### ISSUE THREAD

**Issue by bwubb** [Illumina/SpliceAI#91]
Hello.

I definitely, successfully, ran spliceai from commandline a few weeks ago. Now when I try on a new set of data, Im met with a tensorflow error? Im unable to rerun spliceai on the previously successful data as well. I dont think anything really changed about my venv.

```
(venv) [bwubb@cybertron S0626671]$spliceai -I haplotype.chr22.vcf -R ~/resources/Genomes/Human/GRCh37/human_g1k_v37.fasta -A grch37 -O haplotype.chr22.spliceai.vcf
2021-11-18 08:51:35.216917: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/bwubb/.conda/envs/venv/bin/spliceai", line 10, in <module>
    sys.exit(main())
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/spliceai/__main__.py", line 69, in main
    ann = Annotator(args.R, args.A)
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/spliceai/utils.py", line 44, in __init__
    self.models = [load_model(resource_filename(__name__, x)) for x in paths]
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/spliceai/utils.py", line 44, in <listcomp>
    self.models = [load_model(resource_filename(__name__, x)) for x in paths]
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/saving/save.py", line 200, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/saving/hdf5_format.py", line 180, in load_model_from_hdf5
    model = model_config_lib.model_from_config(model_config,
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/saving/model_config.py", line 52, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/layers/serialization.py", line 208, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/utils/generic_utils.py", line 674, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/engine/training.py", line 2397, in from_config
    functional.reconstruct_from_config(config, custom_objects))
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/engine/functional.py", line 1283, in reconstruct_from_config
    process_node(layer, node_data)
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/engine/functional.py", line 1231, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/engine/base_layer.py", line 976, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1114, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/engine/base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/engine/base_layer.py", line 886, in _infer_output_signature
    self._maybe_build(inputs)
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/engine/base_layer.py", line 2659, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/layers/convolutional.py", line 197, in build
    self.kernel = self.add_weight(
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/engine/base_layer.py", line 647, in add_weight
    variable = self._add_variable_with_custom_getter(
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 813, in _add_variable_with_custom_getter
    new_variable = getter(
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/keras/engine/base_layer_utils.py", line 117, in make_variable
    return tf.compat.v1.Variable(
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 266, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 212, in _variable_v1_call
    return previous_getter(
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 205, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/tensorflow/python/ops/variable_scope.py", line 2612, in default_variable_creator
    return resource_variable_ops.ResourceVariable(
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 270, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1602, in __init__
    self._init_from_args(
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1756, in _init_from_args
    handle = eager_safe_variable_handle(
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 238, in eager_safe_variable_handle
    return _variable_handle_from_shape_and_dtype(shape, dtype, shared_name, name,
  File "/home/bwubb/.conda/envs/venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 178, in _variable_handle_from_shape_and_dtype
    cpp_shape_inference_pb2.CppShapeInferenceResult.HandleShapeAndType(
TypeError: Parameter to MergeFrom() must be instance of same class: expected tensorflow.TensorShapeProto got tensorflow.TensorShapeProto.
```

Ive tried the simple things, like updating spliceai and tensorflow. I havent seen this issue reported on spliceai, Im not sure what is happening differently. Thank you.

-bwubb

**Comment by kishorejaganathan** [comment]
Which versions of Keras and Tensorflow are you using? Can you try creating a copy in a fresh environment and see if that helps?
