### ISSUE TITLE
NameError: name 'CVM' is not defined

### ISSUE THREAD

**Issue by KunFang93** [Illumina/SpliceAI#97]
Hi, 

Thanks for providing this awesome tool! I get this error when I tried to run the example codes on our lab server under **3. Can SpliceAI be used to score custom sequences?**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/keras/engine/saving.py", line 274, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/keras/engine/saving.py", line 627, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/keras/layers/__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/keras/engine/network.py", line 1075, in from_config
    process_node(layer, node_data)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/keras/engine/network.py", line 1025, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/keras/layers/convolutional.py", line 141, in build
    constraint=self.kernel_constraint)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/keras/engine/base_layer.py", line 279, in add_weight
    weight = K.variable(initializer(shape, dtype=dtype),
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/keras/initializers.py", line 227, in __call__
    dtype=dtype, seed=self.seed)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 2706, in random_uniform
    return rng.uniform(shape, low=minval, high=maxval, dtype=dtype)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/theano/sandbox/rng_mrg.py", line 872, in uniform
    rstates = self.get_substream_rstates(nstreams, dtype)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/theano/configparser.py", line 117, in res
    return f(*args, **kwargs)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/theano/sandbox/rng_mrg.py", line 779, in get_substream_rstates
    multMatVect(rval[0], A1p72, M1, A2p72, M2)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/theano/sandbox/rng_mrg.py", line 62, in multMatVect
    [A_sym, s_sym, m_sym, A2_sym, s2_sym, m2_sym], o, profile=False)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/theano/compile/function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/theano/compile/function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/theano/gof/vm.py", line 1142, in make_all
    self.updated_vars,
  File "/data/kun/miniconda3/envs/spliceai/lib/python3.6/site-packages/theano/gof/vm.py", line 992, in make_vm
    vm = CVM(
NameError: name 'CVM' is not defined
```
I used this command to build the conda environment
```
conda create -n spliceai tensorflow=1.9.0 h5py==2.10.0 python=3.6
conda activate spliceai
conda install spliceai
```

Besides, I am not sure what is the mean of _acceptor_prob_ and _donor_prob_. Are those prob considered as the score used in the paper? And how could I tell which nucleotide is the potential acceptor site from the acceptor_prob? 

Thanks in advance!
Kun

**Comment by kishorejaganathan** [comment]
The error lines seem to have references to Theano, which is surprising. Are you sure this is a fresh conda environment? Acceptor prob and donor prob are the same length as the input sequence, the i'th index refers to the i'th nucleotide in the input sequence and the corresponding acceptor and donor probabilities. The score we use in the paper is for variants, these vectors are intermediate vectors in the "delta score" calculations (see methods section, delta score subsection)

**Comment by KunFang93** [comment]
Thanks for your prompt reply! Wired, I created the new environment with the conda command that I listed. Understand~ I am still have one question: in fig.1A, the cartoon indicates that the spliceai is a classification model. In this case, how could I get the classification results from the acceptor_prob or donor_prob?

**Comment by kishorejaganathan** [comment]
You can use a threshold of 0.5 to binarize the probabilities and make it a classification result.

**Comment by KunFang93** [comment]
Understand~ thanks!
